### A.2.1 标量、向量、矩阵和张量
#### 代码清单 A-1 创建PyTorch张量

In [12]:
import torch
tensor0d = torch.tensor(1) # 从 Python 整数创建一个零维张量（标量）
print(tensor0d)

tensor(1)


In [13]:
tensor1d = torch.tensor([1, 2, 3]) # 从 Python 列表创建一个一维张量（向量）
print(tensor1d)

tensor([1, 2, 3])


In [14]:
tensor2d = torch.tensor([[1, 2], [3, 4]]) # 从 Python 嵌套列表创建一个二维张量（矩阵）
print(tensor2d)

tensor([[1, 2],
        [3, 4]])


In [15]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 从 Python 嵌套列表创建一个三维张量
print(tensor3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### A.2.2 张量数据类型

In [10]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [11]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [16]:
# 使用 .to 更改精度
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


### A.2.3 常见的 Pytorch 张量操作

In [17]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2d)
# .shape 属性允许我们访问张量的形状
print(tensor2d.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [18]:
# 使用 .reshape() 方法改变张量的形状
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [20]:
# 在 PyTorch 中，重塑张量更常用的命令是 .view()
print(tensor2d.view(3, 2))
# .view() 方法与 .reshape() 方法不同，.view() 方法会改变张量的内存布局，而 .reshape() 方法会返回一个新的张量，可能会复制数据。因此，在使用 .view() 方法时，必须确保张量是连续的（即在内存中是连续存储的）。如果张量不是连续的，则需要先调用 .contiguous() 方法将其转换为连续的张量，然后再调用 .view() 方法。

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [22]:
# 使用 .T 属性转置张量，沿对角线翻转
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [23]:
# PyTorch 中常用的矩阵相乘方法
# 使用 .matmul() 方法计算张量的乘积
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [24]:
# 也可以使用 @ 运算符计算张量的乘积
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])
