### A.3 轻松实现自动微分
#### 代码清单 A-3 通过 autograd 计算梯度

In [1]:
import torch
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph= True) # 默认情况下，PyTorch 在计算梯度后会销毁计算图以释放内存。然而，由于我们即将再次使用这个计算图，因此可以设置 retain_graph=True,使其保留在内存中
grad_L_b = grad(loss, b, retain_graph= True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [2]:
loss.backward() # 反向传播，计算 w1 和 b 的梯度
print(w1.grad) # 输出 w1 的梯度
print(b.grad) # 输出 b 的梯度

tensor([-0.0898])
tensor([-0.0817])
